site_name: My Docs
site_url: https://docs.designplace.dk
theme:
  name: material
  locale: en
  favicon: assets/images/Logo_Square_Thick.svg
  logo: assets/images/Logo_Square_Thick_White.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - toc.follow
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - navigation.sections

  markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde

extra_css:
  - assets/customization/css/custom.css

plugins:
  - social
  - search:
      lang: en
  - tags:
      tags_file: tags.md
  - encryptcontent:
      remember_password: True
      password_button: True
      encrypted_something:
            data-md-type: [div, id]
      password_inventory:
            ATS: 
                ATS: 'Datait2023!'
                jonas: 'dgb68vep'
            _global:
                jonas: 'dgb68vep'
nav:
  - 'Welcome': 'index.md'
  - Cooking Books:
    - Cooking Books/Cooking Books.md 
    - Cooking Books/Cisco Cooking Book.md
    - Cooking Books/Microsoft Cooking Book.md
  - 'Tags': 'tags.md'
  - 'Designplace': 'https://designplace.dk/'