site_name: My Docs
theme:
  name: material
  locale: en
  favicon: assets/images/Logo_Square_Thick.svg
  logo: assets/images/Logo_Square_Thick_White.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - social:
      enabled: !ENV [CI, false]