site_name: My Docs
site_url: https://docs.designplace.dk
theme:
  name: material
  locale: en
  favicon: assets/images/Logo_Square_Thick.svg
  logo: assets/images/Logo_Square_Thick_White.svg
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.tracking
    - navigation.tabs
    - navigation.path
    - toc.follow
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - abbr
  - admonition
  - def_list
  - footnotes
  - tables
  - pymdownx.details
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.snippets

extra_css:
  - assets/customization/css/custom.css

plugins:
  - social
  - search:
      lang: en
  - tags:
      tags_file: tags.md
  - macros
      
nav:
  - 'Welcome': 'index.md'
  - Cooking books:
    - Cooking books/index.md 
    - Cisco cooking book:
        - Cooking books/Cisco cooking book/index.md
        - Networking/Cisco/Basic.md
        - Networking/Cisco/IP Addressing.md
        - Routing Protocols:
            - Networking/Cisco/Routing protocols/index.md
            - Networking/Cisco/Routing protocols/RIP.md
            - Networking/Cisco/Routing protocols/EIGRP.md
            - Networking/Cisco/Routing protocols/OSPF.md
            - Networking/Cisco/Routing protocols/BGP.md
        #- VRF
        #- DMVPN
        #- ACL & Prefix List
        #- SNMP
        #- DHCP
        #- Syslog
        #- NTP
        #- SNMP
        - Security:
            - Networking\Cisco\Security\index.md
            - Networking\Cisco\Security\Basic.md
            - Networking\Cisco\Security\encryption.md
    - Cheat Sheets:
      - Networking/IPv4 Cheat Sheet.md
      - Networking/IPv6 Cheat Sheet.md
  - 'Tags': 'tags.md'
  - 'Designplace': 'https://designplace.dk/'